# This service account is used to grant privileges to the llama-stack init container
# to update PVC permissions.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  annotations:
    # This annotation is used by OpenShift to assign the anyuid SCC
    # which allows the container to run as any user ID
    openshift.io/scc: anyuid
