exclude: "build/"

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
        exclude: '^(.*\.svg)$'
      - id: no-commit-to-branch
      - id: check-yaml
        args: ["--unsafe"]
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf] # Forces to replace line ending by LF (line feed)
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml

  - repo: local
    hooks:
      - id: linters
        name: Linters
        entry: make lint
        language: system
        pass_filenames: false
        require_serial: true
      - id: generate-manifests
        name: Generate Manifests
        entry: make generate manifests
        language: system
        pass_filenames: false
        require_serial: true
      - id: build-installer
        name: Update Install Script
        entry: make build-installer
        language: system
        pass_filenames: false
        require_serial: true
      - id: generate-api-docs
        name: Generate API Docs
        entry: make api-docs
        language: system
        pass_filenames: false
        require_serial: true
      - id: check-go-error-messages
        name: Check Go Error Messages
        entry: ./hack/check_go_errors.py
        language: python
        types: [go]
      - id: check-workflows-use-hashes
        name: Check GitHub Actions use SHA-pinned actions
        entry: ./hack/check-workflows-uses-hashes.sh
        language: system
        pass_filenames: false
        require_serial: true
        always_run: true
        files: ^\.github/workflows/.*\.ya?ml$
