
name: Generate Release

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a placeholder job to make the workflow discoverable by the GitHub API."
