name: Build Operator Image

on:
  push:
    branches:
       - main
       - odh

permissions:
  actions: write
  contents: read

jobs:
  build-latest-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Login to Quay.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push latest image
        run: make image-build image-push -e IMG=quay.io/opendatahub/llama-stack-k8s-operator:latest
